using AdventOfCode.Year2024;
using System;
using NUnit.Framework;

namespace AdventOfCodeTests.Year2024;

[TestFixture]
public class AoC2024Day08Tests {
    [Test]
    public void Solution1Examples()
    {
        string input = """
                       ............
                       ........0...
                       .....0......
                       .......0....
                       ....0.......
                       ......A.....
                       ............
                       ............
                       ........A...
                       .........A..
                       ............
                       ............
                       """;
        
        long expect = 14;
        
        var instance = new AoC2024Day08(input);
        Assert.That(instance.Solution1(), Is.EqualTo(expect));
    }

    [Test]
    public void Solution1Test() {
        var instance = new AoC2024Day08();
        var result = instance.Solution1();
        Assert.That(result, Is.EqualTo(222));
        Console.WriteLine($"Result: {result}");
    }

    [Test]
    public void Solution2Examples() {
        string input = """
                       ............
                       ........0...
                       .....0......
                       .......0....
                       ....0.......
                       ......A.....
                       ............
                       ............
                       ........A...
                       .........A..
                       ............
                       ............
                       """;
        
        long expect = 34;
        
        var instance = new AoC2024Day08(input);
        Assert.That(instance.Solution2(), Is.EqualTo(expect));
    }

    [Test]
    public void Solution2Test() {
        var instance = new AoC2024Day08();
        var result = instance.Solution2();
        Assert.That(result, Is.EqualTo(884));
        Console.WriteLine($"Result: {result}");
    }
}